FROM node:22-slim
WORKDIR /app

# Инсталираме зависимости за Prisma и инструменти
RUN apt-get update -y && apt-get install -y openssl ca-certificates

COPY package.json ./
RUN npm install

# Копираме Prisma и генерираме клиента
COPY prisma ./prisma/
RUN npx prisma generate

# Създаваме папката за качване и даваме пълни права (за локални тестове)
RUN mkdir -p public/uploads && chmod -R 777 public/uploads

EXPOSE 3000

# Стартираме в dev режим
CMD ["npm", "run", "dev"]