FROM node:22-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl ca-certificates

COPY package.json ./
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "dev"]